id: P010434
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:41.633170
source_metadata:
  id: bdr:W22150
  title: དམྱལ་གླིང་རྫོགས་པ་ཆེན་པོ།
  author: ''
  volumes:
    5e6672f942a844deba069f00c173e9c0:
      image_group_id: I1KG17279
      title: ''
      volume_number: 1
      total_pages: 410
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
