id: I0A2E2A23
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:12:33+00:00'
last_modified: '2022-06-08T13:34:41.755832+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22150
  title: དམྱལ་གླིང་རྫོགས་པ་ཆེན་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7FE1:
      image_group_id: I1KG17279
      title: ''
      total_pages: 410
      order: 1
      base_file: 7FE1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
